name: Build and Deploy Frontend Project

on:
  push:
    branches:
      - main
      - fix/actions
    paths:
      - 'frontend/**'
      - '.github/workflows/build_deploy-frontend.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'
    environment:
      name: 'Azure'  
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: Install and build
        run: |
          cd frontend/smart-power-meter
          npm install
          npm run build
          
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Azure'
    steps:
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "upload"
          app_location: "/frontend/smart-power-meter/out"
          api_location: ""
          skip_app_build: true
