name: Build and Deploy Backend project

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'
    environment:
      name: 'Azure'  
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://acrsmartpowermeterdev.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername }}
        password: ${{ secrets.AzureAppService_ContainerPassword }}
        
    - name: Build and push container image to registry
      uses: docker/build-push-action@v4
      with:
        push: true
        context: backend/
        tags: acrsmartpowermeterdev.azurecr.io/${{ secrets.AzureAppService_ContainerUsername }}/smartpowermeter:${{ github.sha }}
        file: backend/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Azure'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'smartpowermeter-dev'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile }}
        images: 'acrsmartpowermeterdev.azurecr.io/${{ secrets.AzureAppService_ContainerUsername }}/smartpowermeter:${{ github.sha }}'
